-- ELL Reference Data: Countries (ISO 3166 — full list)
-- Owner: ELIZA. Read by LİFFY, LEENA.
-- Ref: ELL_RULES.md v5.1 — R1, R9, ADR-016
-- Replaces 021_core_countries.sql with complete ISO 3166-1 list (249 countries)

CREATE TABLE IF NOT EXISTS core_countries (
  code CHAR(2) PRIMARY KEY,
  code3 CHAR(3) NOT NULL UNIQUE,
  name_en VARCHAR(100) NOT NULL,
  name_tr VARCHAR(100),
  name_fr VARCHAR(100),
  region VARCHAR(50),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_core_countries_active ON core_countries(is_active);
CREATE INDEX IF NOT EXISTS idx_core_countries_region ON core_countries(region);

INSERT INTO core_countries (code, code3, name_en, name_tr, name_fr, region) VALUES
  ('AF', 'AFG', 'Afghanistan', 'Afganistan', 'Afghanistan', 'Asia'),
  ('AL', 'ALB', 'Albania', 'Arnavutluk', 'Albanie', 'Europe'),
  ('DZ', 'DZA', 'Algeria', 'Cezayir', 'Algérie', 'Africa'),
  ('AS', 'ASM', 'American Samoa', 'Amerikan Samoası', 'Samoa américaines', 'Oceania'),
  ('AD', 'AND', 'Andorra', 'Andorra', 'Andorre', 'Europe'),
  ('AO', 'AGO', 'Angola', 'Angola', 'Angola', 'Africa'),
  ('AI', 'AIA', 'Anguilla', 'Anguilla', 'Anguilla', 'Americas'),
  ('AQ', 'ATA', 'Antarctica', 'Antarktika', 'Antarctique', 'Antarctica'),
  ('AG', 'ATG', 'Antigua and Barbuda', 'Antigua ve Barbuda', 'Antigua-et-Barbuda', 'Americas'),
  ('AR', 'ARG', 'Argentina', 'Arjantin', 'Argentine', 'Americas'),
  ('AM', 'ARM', 'Armenia', 'Ermenistan', 'Arménie', 'Asia'),
  ('AW', 'ABW', 'Aruba', 'Aruba', 'Aruba', 'Americas'),
  ('AU', 'AUS', 'Australia', 'Avustralya', 'Australie', 'Oceania'),
  ('AT', 'AUT', 'Austria', 'Avusturya', 'Autriche', 'Europe'),
  ('AZ', 'AZE', 'Azerbaijan', 'Azerbaycan', 'Azerbaïdjan', 'Asia'),
  ('BS', 'BHS', 'Bahamas', 'Bahamalar', 'Bahamas', 'Americas'),
  ('BH', 'BHR', 'Bahrain', 'Bahreyn', 'Bahreïn', 'Asia'),
  ('BD', 'BGD', 'Bangladesh', 'Bangladeş', 'Bangladesh', 'Asia'),
  ('BB', 'BRB', 'Barbados', 'Barbados', 'Barbade', 'Americas'),
  ('BY', 'BLR', 'Belarus', 'Belarus', 'Biélorussie', 'Europe'),
  ('BE', 'BEL', 'Belgium', 'Belçika', 'Belgique', 'Europe'),
  ('BZ', 'BLZ', 'Belize', 'Belize', 'Belize', 'Americas'),
  ('BJ', 'BEN', 'Benin', 'Benin', 'Bénin', 'Africa'),
  ('BM', 'BMU', 'Bermuda', 'Bermuda', 'Bermudes', 'Americas'),
  ('BT', 'BTN', 'Bhutan', 'Butan', 'Bhoutan', 'Asia'),
  ('BO', 'BOL', 'Bolivia', 'Bolivya', 'Bolivie', 'Americas'),
  ('BQ', 'BES', 'Bonaire, Sint Eustatius and Saba', 'Bonaire', 'Bonaire', 'Americas'),
  ('BA', 'BIH', 'Bosnia and Herzegovina', 'Bosna Hersek', 'Bosnie-Herzégovine', 'Europe'),
  ('BW', 'BWA', 'Botswana', 'Botsvana', 'Botswana', 'Africa'),
  ('BV', 'BVT', 'Bouvet Island', 'Bouvet Adası', 'Île Bouvet', 'Antarctica'),
  ('BR', 'BRA', 'Brazil', 'Brezilya', 'Brésil', 'Americas'),
  ('IO', 'IOT', 'British Indian Ocean Territory', 'Britanya Hint Okyanusu Toprakları', 'Territoire britannique', 'Asia'),
  ('BN', 'BRN', 'Brunei Darussalam', 'Brunei', 'Brunei', 'Asia'),
  ('BG', 'BGR', 'Bulgaria', 'Bulgaristan', 'Bulgarie', 'Europe'),
  ('BF', 'BFA', 'Burkina Faso', 'Burkina Faso', 'Burkina Faso', 'Africa'),
  ('BI', 'BDI', 'Burundi', 'Burundi', 'Burundi', 'Africa'),
  ('CV', 'CPV', 'Cabo Verde', 'Yeşil Burun', 'Cap-Vert', 'Africa'),
  ('KH', 'KHM', 'Cambodia', 'Kamboçya', 'Cambodge', 'Asia'),
  ('CM', 'CMR', 'Cameroon', 'Kamerun', 'Cameroun', 'Africa'),
  ('CA', 'CAN', 'Canada', 'Kanada', 'Canada', 'Americas'),
  ('KY', 'CYM', 'Cayman Islands', 'Cayman Adaları', 'Îles Caïmans', 'Americas'),
  ('CF', 'CAF', 'Central African Republic', 'Orta Afrika Cumhuriyeti', 'République centrafricaine', 'Africa'),
  ('TD', 'TCD', 'Chad', 'Çad', 'Tchad', 'Africa'),
  ('CL', 'CHL', 'Chile', 'Şili', 'Chili', 'Americas'),
  ('CN', 'CHN', 'China', 'Çin', 'Chine', 'Asia'),
  ('CX', 'CXR', 'Christmas Island', 'Christmas Adası', 'Île Christmas', 'Oceania'),
  ('CC', 'CCK', 'Cocos (Keeling) Islands', 'Cocos Adaları', 'Îles Cocos', 'Oceania'),
  ('CO', 'COL', 'Colombia', 'Kolombiya', 'Colombie', 'Americas'),
  ('KM', 'COM', 'Comoros', 'Komorlar', 'Comores', 'Africa'),
  ('CG', 'COG', 'Congo', 'Kongo', 'Congo', 'Africa'),
  ('CD', 'COD', 'Congo, Democratic Republic of the', 'Demokratik Kongo', 'République démocratique du Congo', 'Africa'),
  ('CK', 'COK', 'Cook Islands', 'Cook Adaları', 'Îles Cook', 'Oceania'),
  ('CR', 'CRI', 'Costa Rica', 'Kosta Rika', 'Costa Rica', 'Americas'),
  ('CI', 'CIV', "Côte d'Ivoire", 'Fildişi Sahili', "Côte d'Ivoire", 'Africa'),
  ('HR', 'HRV', 'Croatia', 'Hırvatistan', 'Croatie', 'Europe'),
  ('CU', 'CUB', 'Cuba', 'Küba', 'Cuba', 'Americas'),
  ('CW', 'CUW', 'Curaçao', 'Curaçao', 'Curaçao', 'Americas'),
  ('CY', 'CYP', 'Cyprus', 'Kıbrıs', 'Chypre', 'Europe'),
  ('CZ', 'CZE', 'Czechia', 'Çekya', 'Tchéquie', 'Europe'),
  ('DK', 'DNK', 'Denmark', 'Danimarka', 'Danemark', 'Europe'),
  ('DJ', 'DJI', 'Djibouti', 'Cibuti', 'Djibouti', 'Africa'),
  ('DM', 'DMA', 'Dominica', 'Dominika', 'Dominique', 'Americas'),
  ('DO', 'DOM', 'Dominican Republic', 'Dominik Cumhuriyeti', 'République dominicaine', 'Americas'),
  ('EC', 'ECU', 'Ecuador', 'Ekvador', 'Équateur', 'Americas'),
  ('EG', 'EGY', 'Egypt', 'Mısır', 'Égypte', 'Africa'),
  ('SV', 'SLV', 'El Salvador', 'El Salvador', 'Salvador', 'Americas'),
  ('GQ', 'GNQ', 'Equatorial Guinea', 'Ekvator Ginesi', 'Guinée équatoriale', 'Africa'),
  ('ER', 'ERI', 'Eritrea', 'Eritre', 'Érythrée', 'Africa'),
  ('EE', 'EST', 'Estonia', 'Estonya', 'Estonie', 'Europe'),
  ('SZ', 'SWZ', 'Eswatini', 'Esvatini', 'Eswatini', 'Africa'),
  ('ET', 'ETH', 'Ethiopia', 'Etiyopya', 'Éthiopie', 'Africa'),
  ('FK', 'FLK', 'Falkland Islands', 'Falkland Adaları', 'Îles Malouines', 'Americas'),
  ('FO', 'FRO', 'Faroe Islands', 'Faroe Adaları', 'Îles Féroé', 'Europe'),
  ('FJ', 'FJI', 'Fiji', 'Fiji', 'Fidji', 'Oceania'),
  ('FI', 'FIN', 'Finland', 'Finlandiya', 'Finlande', 'Europe'),
  ('FR', 'FRA', 'France', 'Fransa', 'France', 'Europe'),
  ('GF', 'GUF', 'French Guiana', 'Fransız Guyanası', 'Guyane française', 'Americas'),
  ('PF', 'PYF', 'French Polynesia', 'Fransız Polinezyası', 'Polynésie française', 'Oceania'),
  ('TF', 'ATF', 'French Southern Territories', 'Fransız Güney Toprakları', 'Terres australes françaises', 'Antarctica'),
  ('GA', 'GAB', 'Gabon', 'Gabon', 'Gabon', 'Africa'),
  ('GM', 'GMB', 'Gambia', 'Gambiya', 'Gambie', 'Africa'),
  ('GE', 'GEO', 'Georgia', 'Gürcistan', 'Géorgie', 'Asia'),
  ('DE', 'DEU', 'Germany', 'Almanya', 'Allemagne', 'Europe'),
  ('GH', 'GHA', 'Ghana', 'Gana', 'Ghana', 'Africa'),
  ('GI', 'GIB', 'Gibraltar', 'Cebelitarık', 'Gibraltar', 'Europe'),
  ('GR', 'GRC', 'Greece', 'Yunanistan', 'Grèce', 'Europe'),
  ('GL', 'GRL', 'Greenland', 'Grönland', 'Groenland', 'Americas'),
  ('GD', 'GRD', 'Grenada', 'Grenada', 'Grenade', 'Americas'),
  ('GP', 'GLP', 'Guadeloupe', 'Guadeloupe', 'Guadeloupe', 'Americas'),
  ('GU', 'GUM', 'Guam', 'Guam', 'Guam', 'Oceania'),
  ('GT', 'GTM', 'Guatemala', 'Guatemala', 'Guatemala', 'Americas'),
  ('GG', 'GGY', 'Guernsey', 'Guernsey', 'Guernesey', 'Europe'),
  ('GN', 'GIN', 'Guinea', 'Gine', 'Guinée', 'Africa'),
  ('GW', 'GNB', 'Guinea-Bissau', 'Gine-Bissau', 'Guinée-Bissau', 'Africa'),
  ('GY', 'GUY', 'Guyana', 'Guyana', 'Guyana', 'Americas'),
  ('HT', 'HTI', 'Haiti', 'Haiti', 'Haïti', 'Americas'),
  ('HM', 'HMD', 'Heard Island and McDonald Islands', 'Heard Adası', 'Île Heard', 'Antarctica'),
  ('VA', 'VAT', 'Holy See', 'Vatikan', 'Saint-Siège', 'Europe'),
  ('HN', 'HND', 'Honduras', 'Honduras', 'Honduras', 'Americas'),
  ('HK', 'HKG', 'Hong Kong', 'Hong Kong', 'Hong Kong', 'Asia'),
  ('HU', 'HUN', 'Hungary', 'Macaristan', 'Hongrie', 'Europe'),
  ('IS', 'ISL', 'Iceland', 'İzlanda', 'Islande', 'Europe'),
  ('IN', 'IND', 'India', 'Hindistan', 'Inde', 'Asia'),
  ('ID', 'IDN', 'Indonesia', 'Endonezya', 'Indonésie', 'Asia'),
  ('IR', 'IRN', 'Iran', 'İran', 'Iran', 'Asia'),
  ('IQ', 'IRQ', 'Iraq', 'Irak', 'Irak', 'Asia'),
  ('IE', 'IRL', 'Ireland', 'İrlanda', 'Irlande', 'Europe'),
  ('IM', 'IMN', 'Isle of Man', 'Man Adası', 'Île de Man', 'Europe'),
  ('IL', 'ISR', 'Israel', 'İsrail', 'Israël', 'Asia'),
  ('IT', 'ITA', 'Italy', 'İtalya', 'Italie', 'Europe'),
  ('JM', 'JAM', 'Jamaica', 'Jamaika', 'Jamaïque', 'Americas'),
  ('JP', 'JPN', 'Japan', 'Japonya', 'Japon', 'Asia'),
  ('JE', 'JEY', 'Jersey', 'Jersey', 'Jersey', 'Europe'),
  ('JO', 'JOR', 'Jordan', 'Ürdün', 'Jordanie', 'Asia'),
  ('KZ', 'KAZ', 'Kazakhstan', 'Kazakistan', 'Kazakhstan', 'Asia'),
  ('KE', 'KEN', 'Kenya', 'Kenya', 'Kenya', 'Africa'),
  ('KI', 'KIR', 'Kiribati', 'Kiribati', 'Kiribati', 'Oceania'),
  ('KP', 'PRK', "Korea, Democratic People's Republic of", 'Kuzey Kore', 'Corée du Nord', 'Asia'),
  ('KR', 'KOR', 'Korea, Republic of', 'Güney Kore', 'Corée du Sud', 'Asia'),
  ('KW', 'KWT', 'Kuwait', 'Kuveyt', 'Koweït', 'Asia'),
  ('KG', 'KGZ', 'Kyrgyzstan', 'Kırgızistan', 'Kirghizistan', 'Asia'),
  ('LA', 'LAO', "Lao People's Democratic Republic", 'Laos', 'Laos', 'Asia'),
  ('LV', 'LVA', 'Latvia', 'Letonya', 'Lettonie', 'Europe'),
  ('LB', 'LBN', 'Lebanon', 'Lübnan', 'Liban', 'Asia'),
  ('LS', 'LSO', 'Lesotho', 'Lesotho', 'Lesotho', 'Africa'),
  ('LR', 'LBR', 'Liberia', 'Liberya', 'Libéria', 'Africa'),
  ('LY', 'LBY', 'Libya', 'Libya', 'Libye', 'Africa'),
  ('LI', 'LIE', 'Liechtenstein', 'Lihtenştayn', 'Liechtenstein', 'Europe'),
  ('LT', 'LTU', 'Lithuania', 'Litvanya', 'Lituanie', 'Europe'),
  ('LU', 'LUX', 'Luxembourg', 'Lüksemburg', 'Luxembourg', 'Europe'),
  ('MO', 'MAC', 'Macao', 'Makao', 'Macao', 'Asia'),
  ('MG', 'MDG', 'Madagascar', 'Madagaskar', 'Madagascar', 'Africa'),
  ('MW', 'MWI', 'Malawi', 'Malavi', 'Malawi', 'Africa'),
  ('MY', 'MYS', 'Malaysia', 'Malezya', 'Malaisie', 'Asia'),
  ('MV', 'MDV', 'Maldives', 'Maldivler', 'Maldives', 'Asia'),
  ('ML', 'MLI', 'Mali', 'Mali', 'Mali', 'Africa'),
  ('MT', 'MLT', 'Malta', 'Malta', 'Malte', 'Europe'),
  ('MH', 'MHL', 'Marshall Islands', 'Marshall Adaları', 'Îles Marshall', 'Oceania'),
  ('MQ', 'MTQ', 'Martinique', 'Martinik', 'Martinique', 'Americas'),
  ('MR', 'MRT', 'Mauritania', 'Moritanya', 'Mauritanie', 'Africa'),
  ('MU', 'MUS', 'Mauritius', 'Mauritius', 'Maurice', 'Africa'),
  ('YT', 'MYT', 'Mayotte', 'Mayotte', 'Mayotte', 'Africa'),
  ('MX', 'MEX', 'Mexico', 'Meksika', 'Mexique', 'Americas'),
  ('FM', 'FSM', 'Micronesia', 'Mikronezya', 'Micronésie', 'Oceania'),
  ('MD', 'MDA', 'Moldova', 'Moldova', 'Moldavie', 'Europe'),
  ('MC', 'MCO', 'Monaco', 'Monako', 'Monaco', 'Europe'),
  ('MN', 'MNG', 'Mongolia', 'Moğolistan', 'Mongolie', 'Asia'),
  ('ME', 'MNE', 'Montenegro', 'Karadağ', 'Monténégro', 'Europe'),
  ('MS', 'MSR', 'Montserrat', 'Montserrat', 'Montserrat', 'Americas'),
  ('MA', 'MAR', 'Morocco', 'Fas', 'Maroc', 'Africa'),
  ('MZ', 'MOZ', 'Mozambique', 'Mozambik', 'Mozambique', 'Africa'),
  ('MM', 'MMR', 'Myanmar', 'Myanmar', 'Birmanie', 'Asia'),
  ('NA', 'NAM', 'Namibia', 'Namibya', 'Namibie', 'Africa'),
  ('NR', 'NRU', 'Nauru', 'Nauru', 'Nauru', 'Oceania'),
  ('NP', 'NPL', 'Nepal', 'Nepal', 'Népal', 'Asia'),
  ('NL', 'NLD', 'Netherlands', 'Hollanda', 'Pays-Bas', 'Europe'),
  ('NC', 'NCL', 'New Caledonia', 'Yeni Kaledonya', 'Nouvelle-Calédonie', 'Oceania'),
  ('NZ', 'NZL', 'New Zealand', 'Yeni Zelanda', 'Nouvelle-Zélande', 'Oceania'),
  ('NI', 'NIC', 'Nicaragua', 'Nikaragua', 'Nicaragua', 'Americas'),
  ('NE', 'NER', 'Niger', 'Nijer', 'Niger', 'Africa'),
  ('NG', 'NGA', 'Nigeria', 'Nijerya', 'Nigéria', 'Africa'),
  ('NU', 'NIU', 'Niue', 'Niue', 'Niue', 'Oceania'),
  ('NF', 'NFK', 'Norfolk Island', 'Norfolk Adası', 'Île Norfolk', 'Oceania'),
  ('MK', 'MKD', 'North Macedonia', 'Kuzey Makedonya', 'Macédoine du Nord', 'Europe'),
  ('MP', 'MNP', 'Northern Mariana Islands', 'Kuzey Mariana Adaları', 'Îles Mariannes du Nord', 'Oceania'),
  ('NO', 'NOR', 'Norway', 'Norveç', 'Norvège', 'Europe'),
  ('OM', 'OMN', 'Oman', 'Umman', 'Oman', 'Asia'),
  ('PK', 'PAK', 'Pakistan', 'Pakistan', 'Pakistan', 'Asia'),
  ('PW', 'PLW', 'Palau', 'Palau', 'Palaos', 'Oceania'),
  ('PS', 'PSE', 'Palestine', 'Filistin', 'Palestine', 'Asia'),
  ('PA', 'PAN', 'Panama', 'Panama', 'Panama', 'Americas'),
  ('PG', 'PNG', 'Papua New Guinea', 'Papua Yeni Gine', 'Papouasie-Nouvelle-Guinée', 'Oceania'),
  ('PY', 'PRY', 'Paraguay', 'Paraguay', 'Paraguay', 'Americas'),
  ('PE', 'PER', 'Peru', 'Peru', 'Pérou', 'Americas'),
  ('PH', 'PHL', 'Philippines', 'Filipinler', 'Philippines', 'Asia'),
  ('PN', 'PCN', 'Pitcairn', 'Pitcairn', 'Pitcairn', 'Oceania'),
  ('PL', 'POL', 'Poland', 'Polonya', 'Pologne', 'Europe'),
  ('PT', 'PRT', 'Portugal', 'Portekiz', 'Portugal', 'Europe'),
  ('PR', 'PRI', 'Puerto Rico', 'Porto Riko', 'Porto Rico', 'Americas'),
  ('QA', 'QAT', 'Qatar', 'Katar', 'Qatar', 'Asia'),
  ('RE', 'REU', 'Réunion', 'Réunion', 'Réunion', 'Africa'),
  ('RO', 'ROU', 'Romania', 'Romanya', 'Roumanie', 'Europe'),
  ('RU', 'RUS', 'Russian Federation', 'Rusya', 'Russie', 'Europe'),
  ('RW', 'RWA', 'Rwanda', 'Ruanda', 'Rwanda', 'Africa'),
  ('BL', 'BLM', 'Saint Barthélemy', 'Saint-Barthélemy', 'Saint-Barthélemy', 'Americas'),
  ('SH', 'SHN', 'Saint Helena', 'Saint Helena', 'Sainte-Hélène', 'Africa'),
  ('KN', 'KNA', 'Saint Kitts and Nevis', 'Saint Kitts ve Nevis', 'Saint-Christophe-et-Niévès', 'Americas'),
  ('LC', 'LCA', 'Saint Lucia', 'Saint Lucia', 'Sainte-Lucie', 'Americas'),
  ('MF', 'MAF', 'Saint Martin (French part)', 'Saint-Martin', 'Saint-Martin', 'Americas'),
  ('PM', 'SPM', 'Saint Pierre and Miquelon', 'Saint Pierre ve Miquelon', 'Saint-Pierre-et-Miquelon', 'Americas'),
  ('VC', 'VCT', 'Saint Vincent and the Grenadines', 'Saint Vincent', 'Saint-Vincent', 'Americas'),
  ('WS', 'WSM', 'Samoa', 'Samoa', 'Samoa', 'Oceania'),
  ('SM', 'SMR', 'San Marino', 'San Marino', 'Saint-Marin', 'Europe'),
  ('ST', 'STP', 'Sao Tome and Principe', 'Sao Tome', 'Sao Tomé', 'Africa'),
  ('SA', 'SAU', 'Saudi Arabia', 'Suudi Arabistan', 'Arabie saoudite', 'Asia'),
  ('SN', 'SEN', 'Senegal', 'Senegal', 'Sénégal', 'Africa'),
  ('RS', 'SRB', 'Serbia', 'Sırbistan', 'Serbie', 'Europe'),
  ('SC', 'SYC', 'Seychelles', 'Seyşeller', 'Seychelles', 'Africa'),
  ('SL', 'SLE', 'Sierra Leone', 'Sierra Leone', 'Sierra Leone', 'Africa'),
  ('SG', 'SGP', 'Singapore', 'Singapur', 'Singapour', 'Asia'),
  ('SX', 'SXM', 'Sint Maarten (Dutch part)', 'Sint Maarten', 'Saint-Martin', 'Americas'),
  ('SK', 'SVK', 'Slovakia', 'Slovakya', 'Slovaquie', 'Europe'),
  ('SI', 'SVN', 'Slovenia', 'Slovenya', 'Slovénie', 'Europe'),
  ('SB', 'SLB', 'Solomon Islands', 'Solomon Adaları', 'Îles Salomon', 'Oceania'),
  ('SO', 'SOM', 'Somalia', 'Somali', 'Somalie', 'Africa'),
  ('ZA', 'ZAF', 'South Africa', 'Güney Afrika', 'Afrique du Sud', 'Africa'),
  ('GS', 'SGS', 'South Georgia', 'Güney Georgia', 'Géorgie du Sud', 'Antarctica'),
  ('SS', 'SSD', 'South Sudan', 'Güney Sudan', 'Soudan du Sud', 'Africa'),
  ('ES', 'ESP', 'Spain', 'İspanya', 'Espagne', 'Europe'),
  ('LK', 'LKA', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Asia'),
  ('SD', 'SDN', 'Sudan', 'Sudan', 'Soudan', 'Africa'),
  ('SR', 'SUR', 'Suriname', 'Surinam', 'Suriname', 'Americas'),
  ('SJ', 'SJM', 'Svalbard and Jan Mayen', 'Svalbard', 'Svalbard', 'Europe'),
  ('SE', 'SWE', 'Sweden', 'İsveç', 'Suède', 'Europe'),
  ('CH', 'CHE', 'Switzerland', 'İsviçre', 'Suisse', 'Europe'),
  ('SY', 'SYR', 'Syrian Arab Republic', 'Suriye', 'Syrie', 'Asia'),
  ('TW', 'TWN', 'Taiwan', 'Tayvan', 'Taïwan', 'Asia'),
  ('TJ', 'TJK', 'Tajikistan', 'Tacikistan', 'Tadjikistan', 'Asia'),
  ('TZ', 'TZA', 'Tanzania', 'Tanzanya', 'Tanzanie', 'Africa'),
  ('TH', 'THA', 'Thailand', 'Tayland', 'Thaïlande', 'Asia'),
  ('TL', 'TLS', 'Timor-Leste', 'Doğu Timor', 'Timor oriental', 'Asia'),
  ('TG', 'TGO', 'Togo', 'Togo', 'Togo', 'Africa'),
  ('TK', 'TKL', 'Tokelau', 'Tokelau', 'Tokelau', 'Oceania'),
  ('TO', 'TON', 'Tonga', 'Tonga', 'Tonga', 'Oceania'),
  ('TT', 'TTO', 'Trinidad and Tobago', 'Trinidad ve Tobago', 'Trinité-et-Tobago', 'Americas'),
  ('TN', 'TUN', 'Tunisia', 'Tunus', 'Tunisie', 'Africa'),
  ('TR', 'TUR', 'Turkey', 'Türkiye', 'Turquie', 'Asia'),
  ('TM', 'TKM', 'Turkmenistan', 'Türkmenistan', 'Turkménistan', 'Asia'),
  ('TC', 'TCA', 'Turks and Caicos Islands', 'Turks ve Caicos', 'Îles Turks-et-Caïcos', 'Americas'),
  ('TV', 'TUV', 'Tuvalu', 'Tuvalu', 'Tuvalu', 'Oceania'),
  ('UG', 'UGA', 'Uganda', 'Uganda', 'Ouganda', 'Africa'),
  ('UA', 'UKR', 'Ukraine', 'Ukrayna', 'Ukraine', 'Europe'),
  ('AE', 'ARE', 'United Arab Emirates', 'Birleşik Arap Emirlikleri', 'Émirats arabes unis', 'Asia'),
  ('GB', 'GBR', 'United Kingdom', 'Birleşik Krallık', 'Royaume-Uni', 'Europe'),
  ('US', 'USA', 'United States', 'Amerika Birleşik Devletleri', 'États-Unis', 'Americas'),
  ('UM', 'UMI', 'United States Minor Outlying Islands', 'ABD Küçük Adaları', 'Îles mineures américaines', 'Oceania'),
  ('UY', 'URY', 'Uruguay', 'Uruguay', 'Uruguay', 'Americas'),
  ('UZ', 'UZB', 'Uzbekistan', 'Özbekistan', 'Ouzbékistan', 'Asia'),
  ('VU', 'VUT', 'Vanuatu', 'Vanuatu', 'Vanuatu', 'Oceania'),
  ('VE', 'VEN', 'Venezuela', 'Venezuela', 'Venezuela', 'Americas'),
  ('VN', 'VNM', 'Viet Nam', 'Vietnam', 'Viêt Nam', 'Asia'),
  ('VG', 'VGB', 'Virgin Islands (British)', 'Britanya Virgin Adaları', 'Îles Vierges britanniques', 'Americas'),
  ('VI', 'VIR', 'Virgin Islands (U.S.)', 'ABD Virgin Adaları', 'Îles Vierges américaines', 'Americas'),
  ('WF', 'WLF', 'Wallis and Futuna', 'Wallis ve Futuna', 'Wallis-et-Futuna', 'Oceania'),
  ('EH', 'ESH', 'Western Sahara', 'Batı Sahra', 'Sahara occidental', 'Africa'),
  ('YE', 'YEM', 'Yemen', 'Yemen', 'Yémen', 'Asia'),
  ('ZM', 'ZMB', 'Zambia', 'Zambiya', 'Zambie', 'Africa'),
  ('ZW', 'ZWE', 'Zimbabwe', 'Zimbabve', 'Zimbabwe', 'Africa'),
  ('AX', 'ALA', 'Åland Islands', 'Åland Adaları', 'Åland', 'Europe')
ON CONFLICT (code) DO UPDATE SET
  code3 = EXCLUDED.code3,
  name_en = EXCLUDED.name_en,
  name_tr = EXCLUDED.name_tr,
  name_fr = EXCLUDED.name_fr,
  region = EXCLUDED.region,
  updated_at = NOW();
