-- ELL Reference Data: Countries (ISO 3166)
-- Owner: ELIZA. Read by LiFTY, LEENA.
-- Ref: ELL_RULES.md v4 — R1, R9, ADR-016

CREATE TABLE IF NOT EXISTS core_countries (
  code CHAR(2) PRIMARY KEY,
  code3 CHAR(3) NOT NULL UNIQUE,
  name_en VARCHAR(100) NOT NULL,
  name_tr VARCHAR(100),
  name_fr VARCHAR(100),
  region VARCHAR(50),
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_core_countries_active ON core_countries(is_active);
CREATE INDEX IF NOT EXISTS idx_core_countries_region ON core_countries(region);

INSERT INTO core_countries (code, code3, name_en, name_tr, name_fr, region) VALUES
  -- Elan Expo primary markets
  ('TR', 'TUR', 'Turkey', 'Türkiye', 'Turquie', 'MENA'),
  ('NG', 'NGA', 'Nigeria', 'Nijerya', 'Nigéria', 'Africa'),
  ('MA', 'MAR', 'Morocco', 'Fas', 'Maroc', 'MENA'),
  ('KE', 'KEN', 'Kenya', 'Kenya', 'Kenya', 'Africa'),
  ('DZ', 'DZA', 'Algeria', 'Cezayir', 'Algérie', 'MENA'),
  ('GH', 'GHA', 'Ghana', 'Gana', 'Ghana', 'Africa'),
  ('TN', 'TUN', 'Tunisia', 'Tunus', 'Tunisie', 'MENA'),
  ('EG', 'EGY', 'Egypt', 'Mısır', 'Égypte', 'MENA'),
  -- Major exhibitor source countries
  ('CN', 'CHN', 'China', 'Çin', 'Chine', 'Asia'),
  ('IN', 'IND', 'India', 'Hindistan', 'Inde', 'Asia'),
  ('DE', 'DEU', 'Germany', 'Almanya', 'Allemagne', 'Europe'),
  ('IT', 'ITA', 'Italy', 'İtalya', 'Italie', 'Europe'),
  ('FR', 'FRA', 'France', 'Fransa', 'France', 'Europe'),
  ('ES', 'ESP', 'Spain', 'İspanya', 'Espagne', 'Europe'),
  ('GB', 'GBR', 'United Kingdom', 'Birleşik Krallık', 'Royaume-Uni', 'Europe'),
  ('US', 'USA', 'United States', 'Amerika Birleşik Devletleri', 'États-Unis', 'Americas'),
  ('SA', 'SAU', 'Saudi Arabia', 'Suudi Arabistan', 'Arabie saoudite', 'MENA'),
  ('AE', 'ARE', 'United Arab Emirates', 'Birleşik Arap Emirlikleri', 'Émirats arabes unis', 'MENA'),
  ('JP', 'JPN', 'Japan', 'Japonya', 'Japon', 'Asia'),
  ('KR', 'KOR', 'South Korea', 'Güney Kore', 'Corée du Sud', 'Asia'),
  ('BR', 'BRA', 'Brazil', 'Brezilya', 'Brésil', 'Americas'),
  ('PT', 'PRT', 'Portugal', 'Portekiz', 'Portugal', 'Europe'),
  ('NL', 'NLD', 'Netherlands', 'Hollanda', 'Pays-Bas', 'Europe'),
  ('BE', 'BEL', 'Belgium', 'Belçika', 'Belgique', 'Europe'),
  ('PL', 'POL', 'Poland', 'Polonya', 'Pologne', 'Europe'),
  ('RU', 'RUS', 'Russia', 'Rusya', 'Russie', 'Europe'),
  ('UA', 'UKR', 'Ukraine', 'Ukrayna', 'Ukraine', 'Europe'),
  ('GR', 'GRC', 'Greece', 'Yunanistan', 'Grèce', 'Europe'),
  ('CH', 'CHE', 'Switzerland', 'İsviçre', 'Suisse', 'Europe'),
  ('AT', 'AUT', 'Austria', 'Avusturya', 'Autriche', 'Europe'),
  ('SE', 'SWE', 'Sweden', 'İsveç', 'Suède', 'Europe'),
  ('NO', 'NOR', 'Norway', 'Norveç', 'Norvège', 'Europe'),
  ('DK', 'DNK', 'Denmark', 'Danimarka', 'Danemark', 'Europe'),
  ('FI', 'FIN', 'Finland', 'Finlandiya', 'Finlande', 'Europe'),
  ('IL', 'ISR', 'Israel', 'İsrail', 'Israël', 'MENA'),
  ('JO', 'JOR', 'Jordan', 'Ürdün', 'Jordanie', 'MENA'),
  ('LB', 'LBN', 'Lebanon', 'Lübnan', 'Liban', 'MENA'),
  ('QA', 'QAT', 'Qatar', 'Katar', 'Qatar', 'MENA'),
  ('KW', 'KWT', 'Kuwait', 'Kuveyt', 'Koweït', 'MENA'),
  ('BH', 'BHR', 'Bahrain', 'Bahreyn', 'Bahreïn', 'MENA'),
  ('OM', 'OMN', 'Oman', 'Umman', 'Oman', 'MENA'),
  ('IR', 'IRN', 'Iran', 'İran', 'Iran', 'MENA'),
  ('IQ', 'IRQ', 'Iraq', 'Irak', 'Irak', 'MENA'),
  ('PK', 'PAK', 'Pakistan', 'Pakistan', 'Pakistan', 'Asia'),
  ('BD', 'BGD', 'Bangladesh', 'Bangladeş', 'Bangladesh', 'Asia'),
  ('TH', 'THA', 'Thailand', 'Tayland', 'Thaïlande', 'Asia'),
  ('VN', 'VNM', 'Vietnam', 'Vietnam', 'Viêt Nam', 'Asia'),
  ('ID', 'IDN', 'Indonesia', 'Endonezya', 'Indonésie', 'Asia'),
  ('MY', 'MYS', 'Malaysia', 'Malezya', 'Malaisie', 'Asia'),
  ('SG', 'SGP', 'Singapore', 'Singapur', 'Singapour', 'Asia'),
  ('PH', 'PHL', 'Philippines', 'Filipinler', 'Philippines', 'Asia'),
  ('TW', 'TWN', 'Taiwan', 'Tayvan', 'Taïwan', 'Asia'),
  ('HK', 'HKG', 'Hong Kong', 'Hong Kong', 'Hong Kong', 'Asia'),
  ('AU', 'AUS', 'Australia', 'Avustralya', 'Australie', 'Oceania'),
  ('NZ', 'NZL', 'New Zealand', 'Yeni Zelanda', 'Nouvelle-Zélande', 'Oceania'),
  ('CA', 'CAN', 'Canada', 'Kanada', 'Canada', 'Americas'),
  ('MX', 'MEX', 'Mexico', 'Meksika', 'Mexique', 'Americas'),
  ('AR', 'ARG', 'Argentina', 'Arjantin', 'Argentine', 'Americas'),
  ('CL', 'CHL', 'Chile', 'Şili', 'Chili', 'Americas'),
  ('CO', 'COL', 'Colombia', 'Kolombiya', 'Colombie', 'Americas'),
  ('ZA', 'ZAF', 'South Africa', 'Güney Afrika', 'Afrique du Sud', 'Africa'),
  ('ET', 'ETH', 'Ethiopia', 'Etiyopya', 'Éthiopie', 'Africa'),
  ('TZ', 'TZA', 'Tanzania', 'Tanzanya', 'Tanzanie', 'Africa'),
  ('UG', 'UGA', 'Uganda', 'Uganda', 'Ouganda', 'Africa'),
  ('RW', 'RWA', 'Rwanda', 'Ruanda', 'Rwanda', 'Africa'),
  ('CI', 'CIV', 'Cote d''Ivoire', 'Fildişi Sahili', 'Côte d''Ivoire', 'Africa'),
  ('SN', 'SEN', 'Senegal', 'Senegal', 'Sénégal', 'Africa'),
  ('CM', 'CMR', 'Cameroon', 'Kamerun', 'Cameroun', 'Africa'),
  ('LY', 'LBY', 'Libya', 'Libya', 'Libye', 'MENA'),
  ('SD', 'SDN', 'Sudan', 'Sudan', 'Soudan', 'Africa'),
  ('YE', 'YEM', 'Yemen', 'Yemen', 'Yémen', 'MENA'),
  ('SY', 'SYR', 'Syria', 'Suriye', 'Syrie', 'MENA')
ON CONFLICT (code) DO UPDATE SET
  code3 = EXCLUDED.code3,
  name_en = EXCLUDED.name_en,
  name_tr = EXCLUDED.name_tr,
  name_fr = EXCLUDED.name_fr,
  region = EXCLUDED.region,
  updated_at = NOW();
